trigger:
- main   # Trigger when pushing to main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'yugen-rg'        
  location: 'eastus'                   
  deploymentName: 'bicep-vm-deployment'
  templateFile: './template.bicep'
  parametersFile: './parameters.json'

stages:
- stage: Deploy
  displayName: 'Deploy Azure VM via Bicep'
  jobs:
  - job: DeployInfra
    displayName: 'Run Azure CLI Deployment'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Bicep Template'
      inputs:
        azureSubscription: 'github.com_yugendran0705'  
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Starting Bicep deployment..."
          az group create --name $(resourceGroupName) --location $(location)
          az deployment group create \
            --name $(deploymentName) \
            --resource-group $(resourceGroupName) \
            --template-file $(templateFile) \
            --parameters @$(parametersFile)
